# Generated by Django 4.2.8 on 2024-01-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augmentedreality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstats',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelstats',
            name='project_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modelstats',
            name='remaining_displays',
            field=models.IntegerField(default=20),
        ),
    ]
